docs_dir: ./doc
google_analytics: null
site_name: MMMPC
site_url: https://lami.hpc.cineca.it/mmmpc
site_dir: _build/html
theme: mkdocs
use_directory_urls: false
strict: true
# [amelia|cyborg|cerulean|journal|readable|bootstrap|cosmo|united|mkdocs|spacelab|yeti|readthedocs|slate|simplex|flatly]
nav:
- Home: 'index.md'
- Procedure operative:
    - LAMI: 'LAMI.md'
    - icon-2I: 'icon-2I.md'
    - cosmo-5M: 'cosmo-5M.md'
    - cosmo-2I: 'cosmo-2I.md'
#    - moloch-2I: 'moloch-2I.md'
    - MedItaRe: 'MedItaRe.md'
- Accesso ai dati:
    - 'ftp': 'ftp.md'
    - 'arkiweb': 'arkiweb.md'
- Dataset arkimet:
    - 'icon_2I_assim': 'icon_2I_assim.md'
    - 'icon_2I_fcast': 'icon_2I_fcast.md'
    - 'icon_2I_fcruc': 'icon_2I_fcruc.md'
    - 'icon_2I_fcens': 'icon_2I_fcens.md'
    - 'cosmo_5M': 'cosmo_5M.md'
    - 'cosmo_5M_itr': 'cosmo_5M_itr.md'
    - 'cosmo_5M_vprof': 'cosmo_5M_vprof.md'
    - 'cosmo_2I_fcast': 'cosmo_2I_fcast.md'
#    - 'moloch_2I': 'moloch_2I.md'
    - 'swanmed': 'swanmed.md'
    - 'swanita': 'swanita.md'
    - 'swanre': 'swanre.md'
#    - 'dataset_backup': 'dataset_backup.md'

